### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by AGI-admin** [genometools/genometools#889]
## Problem description
We had several of the tests fail,
```
554: gt inlineseq_split (unwritable GFF)                         : failed
     [ problem: unexpected return code: 0 != 1
       in: /usr/local/src/genometools-1.5.10/testsuite/stest_testsuite/test554 ]
555: gt inlineseq_split (unwritable FASTA)                       : failed
     [ problem: unexpected return code: 0 != 1
       in: /usr/local/src/genometools-1.5.10/testsuite/stest_testsuite/test555 ]
1089: genome_stream bindings (output stream)                      : failed
     [ problem: unexpected return code: 0 != 1
       in: /usr/local/src/genometools-1.5.10/testsuite/stest_testsuite/test1089 ]
1111: gt seed_extend: maxmat                                      : failed
     [ problem: unexpected return code: 1 != 0
       in: /usr/local/src/genometools-1.5.10/testsuite/stest_testsuite/test1111 ]
1112: gt seed_extend: symmetry of maxmat/use-apos                 : failed
     [ problem: unexpected return code: 1 != 0
       in: /usr/local/src/genometools-1.5.10/testsuite/stest_testsuite/test1112 ]
1113: gt seed_extend: fstperquery                                 : failed
     [ problem: unexpected return code: 1 != 0
       in: /usr/local/src/genometools-1.5.10/testsuite/stest_testsuite/test1113 ]
1114: gt seed_extend: display arguments                           : failed
     [ problem: unexpected return code: 1 != 0
       in: /usr/local/src/genometools-1.5.10/testsuite/stest_testsuite/test1114 ]
1116: gt dev show_seedext without alignment                       : failed
     [ problem: unexpected return code: 1 != 0
       in: /usr/local/src/genometools-1.5.10/testsuite/stest_testsuite/test1116 ]
1417: gt sketch short test (unwriteable PNG file)                 : failed
     [ problem: unexpected return code: 0 != 1
       in: /usr/local/src/genometools-1.5.10/testsuite/stest_testsuite/test1417 ]
1418: gt sketch short test (unwriteable PDF file)                 : failed
     [ problem: unexpected return code: 0 != 1
       in: /usr/local/src/genometools-1.5.10/testsuite/stest_testsuite/test1418 ]
```

## Exact command line call triggering the problem

```
make test
```

## What GenomeTools version are you reporting an issue for (as output by `gt -version`)?
1.5.10

## Did you compile GenomeTools from source? If so, please state the `make` parameters used.
yes, no parameters

## What operating system (e.g. Ubuntu, Mac OS X), OS version (e.g. 15.10, 10.11) and platform (e.g. x86_64) are you using?
CentOS 6.9 x86_64

**Comment by AGI-admin** [comment]
I noticed in the system messages, several Python crashes relating to this, for example:
```Aug  9 15:58:27 pac abrt: detected unhandled Python exception in '/usr/local/src/genometools-1.5.10/testdata/gtpython/sketch.py'
Aug  9 15:58:28 pac abrt: detected unhandled Python exception in '/usr/local/src/genometools-1.5.10/testdata/gtpython/sketch.py'
Aug  9 16:10:09 pac abrt: detected unhandled Python exception in '/usr/local/src/genometools-1.5.10/testdata/gtpython/sketch_parsed_with_invalid_ordering.py'
Aug  9 16:10:10 pac abrt: detected unhandled Python exception in '/usr/local/src/genometools-1.5.10/testdata/gtpython/sketch_parsed_with_invalid_ordering_2.py'
Aug  9 16:10:10 pac abrt: detected unhandled Python exception in '/usr/local/src/genometools-1.5.10/gtpython/sketch_parsed.py'
Aug  9 16:10:10 pac abrt: detected unhandled Python exception in '/usr/local/src/genometools-1.5.10/gtpython/sketch_constructed.py'
Aug  9 16:10:10 pac abrt: detected unhandled Python exception in '/usr/local/src/genometools-1.5.10/testdata/gtpython/style_serialize.py'
```
etc.  The system Python is rather old, Python 2.6.6, but did not see any reference for a required Python version.  We have Python 2.7 and 3.5 available from Software Collections... do we need to use later Python version for compiling or is there another solution? Thanks

**Comment by gordon** [comment]
Then I would guess that your old Python version is the culprit. We never had the problem you reported on current versions.

**Comment by AGI-admin** [comment]
I did try `make clean` and then enable the newer python with `scl enable rh-python35 bash`, then check `python --version` (it is Python 3.5.1), then run `make` and `make test` again... but now even more tests are failing in addition to the original tests.  I no longer see `unhandled Python exception` in the system messages either.  Are the files in the test directories helpful at all?  For example here is the contents of `/usr/local/src/genometools-1.5.10/testsuite/stest_testsuite/test554`:
```
$ ls -l
total 24
-rw-r--r-- 1 root root  34 Aug 13 17:30 run_1
-rw-r--r-- 1 root root  38 Aug 13 17:30 run_2
-rw-r--r-- 1 root root 250 Aug 13 17:30 run_3
-rw-r--r-- 1 root root   0 Aug 13 17:30 stderr_1
-rw-r--r-- 1 root root   0 Aug 13 17:30 stderr_2
-rw-r--r-- 1 root root   0 Aug 13 17:30 stderr_3
-rw-r--r-- 1 root root   0 Aug 13 17:30 stdout_1
-rw-r--r-- 1 root root   0 Aug 13 17:30 stdout_2
-rw-r--r-- 1 root root   0 Aug 13 17:30 stdout_3
-rw-r--r-- 1 root root 461 Aug 13 17:30 stest_error
-rw-r--r-- 1 root root 819 Aug 13 17:30 tmp.fas
-r--r--r-- 1 root root 696 Aug 13 17:30 unwriteable.gff
$ cat run_1 
$CMD_PREFIX touch unwriteable.gff
$ cat run_2
$CMD_PREFIX chmod u-w unwriteable.gff
$ cat run_3
$CMD_PREFIX env G_DEBUG=gc-friendly G_SLICE=always-malloc GT_SEED=2123552066  /usr/local/src/genometools-1.5.10/bin/gt inlineseq_split -seqfile tmp.fas -gff3file unwriteable.gff /usr/local/src/genometools-1.5.10/testdata//standard_fasta_example.gff3
$ cat stest_error 
Test 554 'gt inlineseq_split (unwritable GFF)': failed:
unexpected return code: 0 != 1:
./stest.rb:286:in `run'
./stest.rb:449:in `run'
testsuite.rb:98:in `run_test'
./gt_inlineseq_include.rb:20
./stest.rb:176:in `test'
./stest.rb:165:in `fork'
./stest.rb:165:in `test'
./stest.rb:121:in `process'
./stest.rb:34:in `run'
./stest.rb:27:in `initialize'
./stest.rb:27:in `new'
./stest.rb:27:in `run'
./stest.rb:26:in `upto'
./stest.rb:26:in `run'
testsuite.rb:267
$ cat tmp.fas 
>ctg123
cttctgggcgtacccgattctcggagaacttgccgcaccattccgccttgtgttcattgctgcctgcatgttcattgtct
acctcggctacgtgtggctatctttcctcggtgccctcgtgcacggagtcgagaaaccaaagaacaaaaaaagaaattaa
aatatttattttgctgtggtttttgatgtgtgttttttataatgatttttgatgtgaccaattgtacttttcctttaaat
gaaatgtaatcttaaatgtatttccgacgaattcgaggcctgaaaagtgtgacgccattcgtatttgatttgggtttact
atcgaataatgagaattttcaggcttaggcttaggcttaggcttaggcttaggcttaggcttaggcttaggcttaggctt
aggcttaggcttaggcttaggcttaggcttaggcttaggcttaggcttagaatctagctagctatccgaaattcgaggcc
tgaaaagtgtgacgccattc
>cdna0123
ttcaagtgctcagtcaatgtgattcacagtatgtcaccaaatattttggcagctttctcaagggatcaaaattatggatc
attatggaatacctcggtggaggctcagcgctcgatttaactaaaagtggaaagctggacgaaagtcatatcgctgtgat
tcttcgcgaaattttgaaaggtctcgagtatctgcatagtgaaagaaaaatccacagagatattaaaggagccaacgttt
tgttggaccgtcaaacagcggctgtaaaaatttgtgattatggttaaagg
$ cat unwriteable.gff 
##gff-version 3
##sequence-region   ctg123 1 1497228
ctg123	.	gene	1000	9000	.	+	.	ID=gene1;Name=EDEN
ctg123	.	TF_binding_site	1000	1012	.	+	.	Parent=gene1
ctg123	.	mRNA	1050	9000	.	+	.	ID=mRNA1;Parent=gene1;Name=EDEN.1
ctg123	.	five_prime_UTR	1050	1200	.	+	.	Parent=mRNA1
ctg123	.	CDS	1201	1500	.	+	0	Parent=mRNA1
ctg123	.	CDS	3000	3902	.	+	0	Parent=mRNA1
ctg123	.	CDS	5000	5500	.	+	0	Parent=mRNA1
ctg123	.	CDS	7000	7600	.	+	0	Parent=mRNA1
ctg123	.	five_prime_UTR	7601	9000	.	+	.	Parent=mRNA1
###
ctg123	.	cDNA_match	1050	1500	5.8e-42	+	.	Target=cdna0123 12 462
ctg123	.	cDNA_match	5000	5500	8.1e-43	+	.	Target=cdna0123 463 963
ctg123	.	cDNA_match	7000	9000	1.4e-40	+	.	Target=cdna0123 964 2964
$ 
```
Thanks
